name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all branches & history are fetched

      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_16.2.app

      - name: Build and Test (iOS)
        run: |
          cd EssentialFeed
          xcodebuild clean build test \
          -project EssentialFeed.xcodeproj \
          -scheme "CI_iOS" \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  build-and-test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_16.2.app

      - name: Build and Test (macOS)
        run: |
          cd EssentialFeed
          xcodebuild clean build test \
          -project EssentialFeed.xcodeproj \
          -scheme "CI_macOS" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
